/** Generated by scripts/build-il-public-snapshot.mjs. Do not edit by hand. */
export const IL_PUBLIC_SNAPSHOT = {
  "version": "investor-il-state-intel-v1",
  "generatedFrom": {
    "nationalRoster": "packages/domain/src/investor-home-intel.ts V1_ROSTER_PRINCIPAL_OFFICE_STATES + V1_SEC_ROSTER",
    "iapdStateCensus": "data/illinois/il-inv-001/iapd-il-census.json"
  },
  "asOf": "2026-09-12",
  "publicationGate": "ON",
  "publicEligibility": "state_page",
  "route": "/illinois",
  "growthClassification": "INTELLIGENCE_GROWTH_HEAVY",
  "uiGrains": {
    "stateIa": "VISIBLE_PUBLIC_METRIC",
    "stateEra": "VISIBLE_PUBLIC_METRIC",
    "notice": "VISIBLE_PUBLIC_METRIC",
    "principalOffice": "VISIBLE_PUBLIC_METRIC",
    "overlapApprovedStateIaNotice": "VISIBLE_SUPPORTING_CONTEXT",
    "sosEnforcement": "VISIBLE_SUPPORTING_CONTEXT",
    "iarPersonUniverse": "INTERNAL_DIAGNOSTIC_ONLY"
  },
  "nationalOverlay": {
    "ilPrincipalOfficeSecIardFirms": 793,
    "grain": "SEC IARD roster firm with principal-office region = IL",
    "source": "IA_FIRM_SEC_Feed_08_27_2026",
    "sourceAsOf": "2026-08-27",
    "publishedAt": "2026-08-27",
    "retrievedAt": "2026-08-28",
    "snapshotAsOf": "2026-08-27",
    "universe": 23622,
    "resolvedPrincipalOfficeRegions": 17997,
    "unresolvedPrincipalOfficeRegions": 5625,
    "shareOfResolvedRegionsPct": 4.41,
    "searchHref": "/firms?state=IL",
    "rawCompilationMainAddrIl": 798,
    "label": "SEC/IARD roster firms with an Illinois principal office",
    "caveat": "This is the national SEC/IARD roster overlay for firms that report an Illinois principal office on the reconciled 23,622-firm geography table (IL = 793). It is not the Illinois state-registered adviser universe, not a federal-covered notice-filing count, and not proof of current Illinois Securities Department authority. ILLINOIS PRINCIPAL OFFICE != ILLINOIS STATE REGISTRATION. These 793 firms already exist in the federal graph and are not net-new organizations. A raw compilation MainAddr=@State=IL count is a different extract and is not this overlay."
  },
  "riaEra": {
    "nationalRiaFacts": 17018,
    "nationalEraFacts": 6604,
    "nationalTotalFacts": 23622,
    "ilPrincipalOfficeSplit": "SOURCE_NOT_SPLIT",
    "caveat": "National roster keeps RIA (17,018) and ERA (6,604) separate. Committed geography is on the combined roster. Illinois principal-office counts are not an RIA-only or ERA-only state denominator. ERA is not an RIA. SEC RIA is not an Illinois state RIA."
  },
  "firmMarket": {
    "raumBandsByIllinoisPrincipalOffice": "SOURCE_NOT_SPLIT",
    "note": "National RIA RAUM bands and Form ADV attributes exist on the federal spine. This snapshot does not invent an Illinois-only size ranking or treat RAUM as investment performance. An Illinois principal office is not Illinois registration."
  },
  "stateRia": {
    "STATE_RIA_BULK_ROSTER": "ACQUIRED_IAPD_STATE_COMPILATION",
    "access": "ACQUIRED",
    "completeStateRiaCount": 855,
    "registrationRows": 855,
    "distinctFirmCrd": 855,
    "approvedDistinctCrd": 855,
    "termrequestDistinctCrd": 0,
    "filter": "StateRgstn/Rgltr/@Cd=IL (registration jurisdiction). Not MainAddr/@State.",
    "currentness": "APPROVED = current state IA in this compilation. TERMREQUEST is not approved current.",
    "source": "IA_FIRM_STATE_Feed_08_27_2026",
    "sourceAsOf": "2026-08-27",
    "publishedAt": "2026-08-27",
    "retrievedAt": "2026-08-28",
    "snapshotAsOf": "2026-08-27",
    "checksumSha256": "4dc5ec13827c2546213fba16d3397448ba5c08cb8c092f1135c405a7f8472eda",
    "releaseLabel": "IA_FIRM_STATE_Feed_08_27_2026",
    "officialUrl": "https://reports.adviserinfo.sec.gov/reports/CompilationReports/IA_FIRM_STATE_Feed_08_27_2026.xml.gz",
    "sosSearch": "OPEN_SEARCH_ONLY",
    "verifyUrl": "https://adviserinfo.sec.gov/",
    "sosHomeUrl": "https://www.ilsos.gov/departments/securities/",
    "sosRegistrationSearchUrl": "https://www.ilsos.gov/departments/securities/secsearch.html",
    "sosAdminActionsUrl": "https://www.ilsos.gov/departments/securities/administrative_actions/home.html",
    "sosAdminActionsSearchUrl": "https://www.ilsos.gov/adminactionssearch/",
    "iapdUrl": "https://adviserinfo.sec.gov/",
    "brokercheckUrl": "https://brokercheck.finra.org/",
    "label": "Illinois state-registered investment-adviser firms",
    "caveat": "IAPD state compilation firms with Illinois as the registration jurisdiction and status APPROVED. This is IARD-derived state registration evidence, not a separately acquired Illinois SOS bulk roster. It is not an SEC RIA count, not a federal-covered notice-filing count, not an ERA count, and not the 793 principal-office overlay. Duplicate/multi-jurisdiction rows were collapsed to distinct firm CRD. State-only CRDs were not minted as public SEC firm profiles and were not added to the 23,622 SEC/IARD roster. The ILSOS registration search covers business brokers and loan brokers, not investment advisers."
  },
  "stateEra": {
    "STATE_ERA_REPORTING": "ACQUIRED_IAPD_STATE_COMPILATION",
    "registrationRows": 55,
    "distinctFirmCrd": 55,
    "activeDistinctCrd": 55,
    "overlapWithStateIa": 0,
    "filter": "ERA/Rgltr/@Cd=IL (reporting jurisdiction). Not address. Not StateRgstn.",
    "source": "IA_FIRM_STATE_Feed_08_27_2026",
    "sourceAsOf": "2026-08-27",
    "retrievedAt": "2026-08-28",
    "label": "Illinois state ERA reporting firms",
    "caveat": "State ERA reporting is not an Illinois state RIA and is not an SEC RIA. Overlap with state IA is zero in this extract."
  },
  "federalNotice": {
    "FEDERAL_COVERED_NOTICE_ROSTER": "ACQUIRED_IAPD_SEC_COMPILATION",
    "access": "ACQUIRED",
    "noticeRows": 3560,
    "noticeFiledDistinctCrd": 3560,
    "noticeStatus": "FILED",
    "filter": "NoticeFiled/States/@RgltrCd=IL",
    "source": "IA_FIRM_SEC_Feed_08_27_2026",
    "sourceAsOf": "2026-08-27",
    "publishedAt": "2026-08-27",
    "retrievedAt": "2026-08-28",
    "snapshotAsOf": "2026-08-27",
    "overlapApprovedStateIa": 1,
    "overlapApprovedStateIaJoinMethod": "exact firm CRD set intersection of APPROVED StateRgstn/Rgltr/@Cd=IL and NoticeFiled/States/@RgltrCd=IL St=FILED",
    "overlapApprovedStateIaCrds": [
      "290683"
    ],
    "overlapApprovedStateIaReading": "The credential classes are separate but the source populations are not perfectly disjoint; one firm CRD appears in both source-defined sets in the 2026-08-27 compilations. Exact-CRD inspection shows CRD 290683 is APPROVED in StateRgstn/Rgltr/@Cd=IL and FILED in NoticeFiled/States/@RgltrCd=IL with FirmType=Registered. Neither classification was discarded.",
    "overlapEraNotice": 0,
    "filedFirmType": {
      "Registered": 3560,
      "ERA": 0,
      "other": 0,
      "blank": 0,
      "raw": [
        [
          "Registered",
          3560
        ]
      ]
    },
    "label": "SEC/IARD firms with an Illinois notice filing",
    "caveat": "Federal-covered / notice-filed is not Illinois state-RIA licensure. Notice-filed is not the 793 principal-office overlay. An Illinois principal office does not prove a current notice filing."
  },
  "iar": {
    "IA_INDVL_FEED": "ACQUIRED_NATIONAL_FEED",
    "illinoisPersonDirectory": "NOT_PUBLISHED",
    "access": "OPEN_SEARCH_ONLY",
    "completeIarCount": "UNKNOWN",
    "grain": "person CRD (not firm CRD)",
    "source": "IA_INDVL_Feed_08_27_2026",
    "sourceAsOf": "2026-08-27",
    "retrievedAt": "2026-08-28",
    "verifyUrl": "https://adviserinfo.sec.gov/",
    "caveat": "The national IAR compilation exists. This ticket does not publish an Illinois person directory. IAR is not the firm. Search V1 remains firm-focused. Complete Illinois IAR universe is UNKNOWN, not zero."
  },
  "brokerDealer": {
    "IL_BD_BULK_ROSTER": "SOURCE_NOT_ACQUIRED",
    "IL_AGENT_BULK_ROSTER": "SOURCE_NOT_ACQUIRED",
    "access": "OPEN_SEARCH_ONLY",
    "completeDealerCount": "UNKNOWN",
    "completeAgentCount": "UNKNOWN",
    "verifyUrl": "https://brokercheck.finra.org/",
    "caveat": "Broker-dealer is not an investment adviser. Registered representative is not an IAR. Illinois SOS Securities Department also regulates securities dealers; FINRA-member firms use CRD. BrokerCheck is not scraped. Search-only is not zero."
  },
  "sosFramework": {
    "regulator": "Illinois Secretary of State, Securities Department",
    "notDfs": true,
    "ruleCitation": "Illinois Securities Law of 1953, 815 ILCS 5",
    "officialHomeUrl": "https://www.ilsos.gov/departments/securities/",
    "officialRegistrationSearchUrl": "https://www.ilsos.gov/departments/securities/secsearch.html",
    "officialAdminActionsUrl": "https://www.ilsos.gov/departments/securities/administrative_actions/home.html",
    "clientThresholdNote": "Illinois investment-adviser firms register through IARD. The ILSOS registration search is for business brokers, business-broker representatives, business opportunities, and loan brokers — not the investment-adviser universe. Current IA verification is IAPD. Do not infer Illinois authority from address, principal office, or name match.",
    "notLegalAdvice": true,
    "retrievedAt": "2026-09-12"
  },
  "enforcement": {
    "pass": "ilsos_administrative_actions_audit",
    "result": "PUBLIC_RESEARCH_PATH",
    "officialIndex": "https://www.ilsos.gov/departments/securities/administrative_actions/home.html",
    "officialSearch": "https://www.ilsos.gov/adminactionssearch/",
    "coverage": "Illinois SOS Securities Department Administrative Actions library (monthly PDFs, 2003–present) plus Administrative Actions Search",
    "REGULATORY_ACTIVITY_COVERAGE": "PUBLIC_RESEARCH_PATH",
    "COMPLETE_REGULATORY_ACTIVITY_COUNT": "UNKNOWN",
    "observationRows": null,
    "distinctCaseNumbers": null,
    "dateMin": null,
    "dateMax": null,
    "rowsWithCrd": null,
    "rowsNameOnly": null,
    "ROWS_ACQUIRED_BY_THIS_TICKET": 0,
    "pdfsDownloaded": 0,
    "exactCrdCrosswalks": 0,
    "doNotCalculateEnforcementRate": true,
    "notInvestmentAdviserEnforcementCensus": true,
    "profileAttachments": [],
    "identityBar": "EXACT_FIRM_CRD, EXACT_PERSON_CRD for person grain only, or exact source-native Illinois SOS matter identifier",
    "nameOnly": "UNSAFE",
    "namePlusCity": "REVIEW_REQUIRED",
    "sourceAsOf": null,
    "retrievedAt": "2026-09-12",
    "snapshotAsOf": "2026-09-12",
    "caveat": "Illinois SOS Administrative Actions are mixed securities matters (issuers, dealers, advisers, individuals, and other actors) published as monthly PDFs and a developing search. No bounded CRD-bearing enforcement table was acquired. Complete Illinois securities-enforcement count is UNKNOWN, not zero. Missing census is not zero enforcement activity. This ticket attached zero exact CRD records and downloaded zero PDFs; those are execution counts, not an Illinois action census. Name-only attachment is unsafe. Administrative action is not an investment-adviser disciplinary census. Order is not a criminal conviction. Consent is not an admission unless the source says so. Fine is not investment loss. No action found is not a clean record."
  },
  "complaints": {
    "publicResearchPath": "https://www.ilsos.gov/departments/securities/",
    "bulkComplaintDataset": "SOURCE_NOT_ACQUIRED",
    "access": "OPEN_SEARCH_ONLY",
    "completeComplaintCount": "UNKNOWN",
    "caveat": "No structured Illinois securities-complaint dataset was acquired. Complaint is not a violation. Investigation is not a finding. Do not answer firm-specific complaint questions with statewide administrative-action libraries."
  },
  "formD": {
    "overlay": "SOURCE_NOT_ACQUIRED",
    "caveat": "FORM D / EFD FILING != ILLINOIS STATE APPROVAL. FORM D FILING != INVESTMENT QUALITY. FORM D FILING != ADVISER."
  },
  "contacts": {
    "policy": "Official/public business sources only. No internet enrichment. No IAPD/BrokerCheck/ILSOS search scrape. No person contact publication from this ticket.",
    "sosSearchScrape": false
  },
  "juiceSqueeze": [
    {
      "decision": "GRABBED — HIGH YIELD",
      "source": "IAPD Illinois state IA registration slice (jurisdiction=IL)"
    },
    {
      "decision": "GRABBED — HIGH YIELD",
      "source": "IAPD Illinois ERA slice"
    },
    {
      "decision": "GRABBED — HIGH YIELD",
      "source": "IAPD Illinois federal notice slice"
    },
    {
      "decision": "GRABBED — HIGH YIELD",
      "source": "Existing IL principal-office overlay (V1_ROSTER_PRINCIPAL_OFFICE_STATES)"
    },
    {
      "decision": "GRABBED — EASY SECONDARY",
      "source": "Illinois SOS Securities Department official verification and administrative-actions paths"
    },
    {
      "decision": "LEFT — SEARCH ONLY",
      "source": "Current IAPD/BrokerCheck/ILSOS interactive verification systems"
    },
    {
      "decision": "LEFT — TOO MUCH WORK FOR CURRENT YIELD",
      "source": "Illinois SOS Administrative Actions monthly PDF census and CRD extraction"
    },
    {
      "decision": "LEFT — TOO MUCH WORK FOR CURRENT YIELD",
      "source": "Individual U4/U5 histories and broker-agent current roster"
    },
    {
      "decision": "LEFT — REQUEST ONLY",
      "source": "FOIA"
    },
    {
      "decision": "LEFT — SHARED / FUTURE",
      "source": "Broad IL corporate entity graph; Form D issuer intelligence"
    },
    {
      "decision": "LEFT — LOCAL / FUTURE",
      "source": "Chicago / Cook / counties / cities"
    }
  ],
  "regulatorMatrix": [
    {
      "credential": "SEC-registered investment adviser",
      "regulator": "U.S. SEC / IARD",
      "identity": "CRD / IARD firm ID; SEC file number",
      "proves": "Federal registration category as reported on Form ADV in the cited extract",
      "doesNotProve": "Illinois state-RIA licensure or current Illinois notice-filing status"
    },
    {
      "credential": "Exempt reporting adviser (ERA)",
      "regulator": "SEC / IARD (and Illinois reporting when applicable)",
      "identity": "CRD / IARD firm ID",
      "proves": "ERA reporting status in the cited extract",
      "doesNotProve": "SEC RIA registration or Illinois state-RIA licensure"
    },
    {
      "credential": "Illinois state-registered investment adviser",
      "regulator": "Illinois Secretary of State, Securities Department / IARD",
      "identity": "Firm CRD / IARD",
      "proves": "Illinois state-IA registration when the official IARD state record says APPROVED",
      "doesNotProve": "SEC registration. Principal-office geography is not this credential."
    },
    {
      "credential": "Federally covered / notice-filed investment adviser",
      "regulator": "Illinois SOS Securities Department (notice) / SEC (federal registration)",
      "identity": "CRD / IARD firm ID",
      "proves": "Notice-filing posture when the official IARD record says FILED",
      "doesNotProve": "Illinois state-RIA licensure"
    },
    {
      "credential": "Investment adviser representative",
      "regulator": "Illinois SOS Securities Department / CRD",
      "identity": "Person CRD (not firm CRD)",
      "proves": "Individual representative reporting when official CRD evidence exists",
      "doesNotProve": "Firm registration. IAR is not the firm. IAR is not a broker-dealer registered representative."
    },
    {
      "credential": "Broker-dealer / registered representative",
      "regulator": "Illinois SOS / FINRA / CRD",
      "identity": "Firm or person CRD",
      "proves": "Broker-dealer or representative registration when official evidence exists",
      "doesNotProve": "Investment-adviser registration"
    },
    {
      "credential": "Illinois SOS administrative action",
      "regulator": "Illinois Secretary of State, Securities Department",
      "identity": "Exact source-native matter identifier; CRD only if source-native",
      "proves": "A public Illinois SOS administrative-action observation when attached by exact identity",
      "doesNotProve": "That every SOS matter is an investment-adviser disciplinary finding or a criminal conviction"
    }
  ],
  "identityRules": {
    "EXACT": [
      "firm CRD/IARD ID",
      "person CRD for person grain only",
      "SEC file number where source-native",
      "exact official Illinois SOS matter identifier"
    ],
    "HIGH_CONFIDENCE": "exact legal name + exact official address for non-adverse descriptive review only",
    "REVIEW_REQUIRED": "name + city, DBA, name variants, address-only",
    "UNSAFE": "name alone — not used for adverse profile attachment"
  },
  "semanticGrainRules": {
    "STATE_RIA_IS_DISTINCT_CREDENTIAL_FROM_SEC_RIA": true,
    "STATE_RIA_IS_DISTINCT_CREDENTIAL_FROM_NOTICE_FILING": true,
    "STATE_RIA_IS_DISTINCT_CREDENTIAL_FROM_STATE_ERA": true,
    "PRINCIPAL_OFFICE_IS_NOT_REGISTRATION": true,
    "REGISTRATION_ROW_IS_DISTINCT_GRAIN_FROM_DISTINCT_FIRM_CRD": true,
    "BROKER_DEALER_IS_NOT_INVESTMENT_ADVISER": true,
    "AGENT_IS_NOT_IAR": true,
    "FIRM_IS_NOT_INDIVIDUAL": true,
    "SOS_ACTION_IS_NOT_IA_DISCIPLINARY_CENSUS": true,
    "COMPLAINT_IS_NOT_VIOLATION": true,
    "RAUM_IS_NOT_PERFORMANCE": true,
    "note": "Credential/grain rules. They do not require disjoint CRD sets or unequal counts."
  },
  "profileAttachments": [],
  "expansionLedger": {
    "PRE_INGEST_CANONICAL_FIRMS": 25777,
    "IL_PRINCIPAL_OFFICE_FIRMS": 793,
    "IL_STATE_IA_ROWS": 855,
    "IL_STATE_IA_DISTINCT_CRDS": 855,
    "IL_STATE_IA_CURRENT_FIRMS": 855,
    "IL_ERA_ROWS": 55,
    "IL_ERA_DISTINCT_CRDS": 55,
    "IL_FEDERAL_NOTICE_ROWS": 3560,
    "IL_FEDERAL_NOTICE_DISTINCT_CRDS": 3560,
    "EXACT_STATE_IA_ERA_OVERLAPS": 0,
    "EXACT_STATE_IA_NOTICE_OVERLAPS": 1,
    "EXACT_ERA_NOTICE_OVERLAPS": 0,
    "IL_IAR_PERSON_ROWS": null,
    "NEW_IL_STATE_IDENTITIES": 910,
    "NEW_IL_STATE_IDENTITIES_DEFINITION": "distinct firm CRDs in IAPD StateRgstn/Rgltr/@Cd=IL plus distinct firm CRDs in ERA/Rgltr/@Cd=IL (overlap 0 in this extract). Not new companies, not public profiles, not a combined Illinois adviser universe.",
    "NET_NEW_CANONICAL_ORGANIZATIONS": 0,
    "NET_NEW_PUBLIC_INVESTOR_PROFILES": 0,
    "EXISTING_ORGANIZATIONS_ENRICHED": 0,
    "PRE_EXISTING_IL_PRINCIPAL_OFFICE_OVERLAY": 793,
    "GRAPH_WRITES": 0,
    "IL_SECURITIES_ENFORCEMENT_OBSERVATIONS": null,
    "REGULATORY_ACTIVITY_COVERAGE": "PUBLIC_RESEARCH_PATH",
    "EXACT_ENFORCEMENT_FIRM_ASSOCIATIONS": 0,
    "REVIEW_REQUIRED_ASSOCIATIONS": 0,
    "REJECTED_NAME_ONLY_ASSOCIATIONS": 0,
    "EXACT_PROFILE_ATTACHMENTS": 0,
    "notes": {
      "overlay": "793 Illinois principal-office firms already existed on the federal SEC/IARD spine before IL-INV-001. This ticket reused the existing canonical overlay. It did not write new principal-office enrichment into those organizations. EXISTING_ORGANIZATIONS_ENRICHED = 0. GRAPH_WRITES = 0.",
      "stateRoster": "IAPD state compilation added 855 distinct Illinois state-IA CRDs and 55 distinct Illinois state-ERA CRDs as state-intelligence identities. They were not minted as canonical organizations or public /firm profiles.",
      "notice": "3,560 notice-filing rows are observations, not extra firms.",
      "activity": "No bounded Illinois SOS IA enforcement table was acquired. Monthly PDF library remains PUBLIC_RESEARCH_PATH. Complete SOS regulatory-activity count is UNKNOWN, not zero."
    }
  },
  "preIngestBaseline": {
    "illinoisPrincipalOfficeFirmsAlreadyInFederalGraph": 793,
    "canonicalFirmsAlreadyPresent": 25777,
    "note": "Recomputed from V1_ROSTER_PRINCIPAL_OFFICE_STATES IL = 793. Do not call these firms new."
  },
  "sourceInventory": [
    {
      "authority": "SEC / IAPD",
      "source": "IA_FIRM_SEC_Feed_08_27_2026",
      "coverageStatus": "ACQUIRED",
      "sourceAsOf": "2026-08-27",
      "retrievedAt": "2026-08-28",
      "count": 23622
    },
    {
      "authority": "IAPD",
      "source": "IA_FIRM_STATE_Feed_08_27_2026",
      "coverageStatus": "ACQUIRED",
      "sourceAsOf": "2026-08-27",
      "retrievedAt": "2026-08-28",
      "count": 855
    },
    {
      "authority": "Illinois SOS Securities Department",
      "source": "department home / IA via IARD",
      "coverageStatus": "ACQUIRED_CONTEXT",
      "sourceAsOf": null,
      "retrievedAt": "2026-09-12",
      "count": null
    },
    {
      "authority": "Illinois SOS Securities Department",
      "source": "Administrative Actions library",
      "coverageStatus": "PUBLIC_RESEARCH_PATH",
      "sourceAsOf": null,
      "retrievedAt": "2026-09-12",
      "count": null
    },
    {
      "authority": "IAPD / BrokerCheck / ILSOS records",
      "source": "interactive verification",
      "coverageStatus": "OPEN_SEARCH_ONLY",
      "sourceAsOf": null,
      "retrievedAt": "2026-09-12",
      "count": null
    }
  ],
  "gaps": [
    "Live ILSOS/IAPD/BrokerCheck verification is OPEN_SEARCH_ONLY; search-only is not zero.",
    "Complete Illinois IAR person universe is UNKNOWN and is not published as a directory.",
    "Complete Illinois broker-dealer and agent rosters are UNKNOWN.",
    "Illinois SOS enforcement is a mixed monthly-PDF library, not a bounded IA census.",
    "No Illinois city/county investor pages.",
    "Form D overlay not acquired."
  ],
  "rejectedJoins": [
    {
      "join": "name-only SOS matter → public firm profile",
      "status": "REJECTED_UNSAFE",
      "count": 0,
      "reason": "Name alone is unsafe for adverse attachment. No bulk SOS table was acquired."
    },
    {
      "join": "person CRD → firm CRD",
      "status": "REJECTED_UNSAFE",
      "count": 0,
      "reason": "Exact person CRD does not become firm CRD."
    },
    {
      "join": "793 principal-office firms → Illinois state IA universe",
      "status": "REJECTED",
      "count": 0,
      "reason": "Principal office is geography, not registration."
    }
  ],
  "rejectedTotals": [
    {
      "total": "Illinois has 793 investment advisers",
      "reason": "793 is SEC/IARD principal-office geography, not a combined Illinois adviser universe."
    },
    {
      "total": "793 + 855 + 55 + 3,560 as Illinois advisers",
      "reason": "Incompatible grains."
    },
    {
      "total": "Missing IAR/BD/complaint counts as zero",
      "reason": "Missing and search-only are unknown, not zero."
    },
    {
      "total": "Illinois SOS regulatory activity rows = 0",
      "reason": "No bounded SOS census was acquired. PUBLIC_RESEARCH_PATH / UNKNOWN is not zero enforcement activity."
    }
  ],
  "semanticGuardrails": [
    "ILLINOIS PRINCIPAL OFFICE != STATE REGISTRATION",
    "SEC RIA != ILLINOIS STATE RIA",
    "STATE RIA != FEDERAL-COVERED NOTICE FILING",
    "RIA != ERA",
    "IAR != FIRM",
    "BROKER-DEALER != IA",
    "REGISTERED REPRESENTATIVE != IAR",
    "RAUM != INVESTMENT PERFORMANCE",
    "COMPLAINT != VIOLATION",
    "SOS ACTION != IA DISCIPLINARY CENSUS",
    "NAME-ONLY ADVERSE MATCH = UNSAFE",
    "MISSING != ZERO",
    "SEARCH-ONLY != ZERO",
    "NO TRUST SCORE",
    "NO PAID RANKING"
  ],
  "fingerprint": "997728ec50c9a913a64283b7a10810440c1e0b88e7fae03a91df58df3997534d"
} as const;
export type IlPublicSnapshot = typeof IL_PUBLIC_SNAPSHOT;
