export type GoldenClassification = 'PASS' | 'PARTIAL' | 'UNSUPPORTED_SAFE' | 'FAIL';
const pass = [
  'CRD 105958','Find CRD 105958','What is a CRD number?','SEC file 801-11953','Find SEC 801-11953','Vanguard','BlackRock','SEC-registered RIAs in Florida','RIAs and ERAs in Florida','what is an RIA','what is an ERA','RIA vs ERA','what is Form ADV','what is RAUM','RIAs with more than $1 billion RAUM','RIAs between $1 billion and $10 billion RAUM','RIAs with zero RAUM','firms with highest RAUM','firms with lowest RAUM','firms reporting asset-based fees','firms reporting hourly fees','firms reporting fixed fees','firms reporting commissions','firms reporting performance-based fees','firms reporting asset-based and hourly compensation','what does asset-based compensation mean','firms affiliated with broker-dealers','firms affiliated with banks','adviser firms in Florida','advisers headquartered in Florida','compare Florida and New Jersey adviser counts','compare RIA and ERA counts','compare RAUM bands','how many RIAs are there','how many ERAs are there','how many investment adviser firms are there','how many Form ADV observations are there','how many firms report asset-based compensation','how many firms report performance-based fees','firms with latest filings','is this adviser registered with the SEC','I want to check the adviser who wants to manage my money','how do I verify an investment adviser','how large is this adviser','what fees does this adviser report','is this adviser affiliated with a broker dealer','investment adviser in ZIP 33441','firm CRD 123456','principal office meaning','SEC file number meaning','Form ADV Item 5.E','Show firms reporting subscription fees','Show firms reporting other compensation','RIA principal offices in Texas','ERA principal offices in Washington','How many RIA firms in Florida','How many ERA firms in California','Compare Texas and Washington RIA counts','Show RIAs under $100 million RAUM','Show RIAs with $10 billion or more RAUM','Show firms alphabetically','Show latest ADV filing dates','What is principal office','Find firm named Vanguard','Firm name BlackRock','Show RIA compensation methods distribution','How are RIAs distributed by RAUM','Which states have the most RIA principal offices','Find CRD 1','CRD 9999999999',
];
const partial = ['ownership evidence for this adviser','who owns this adviser firm','firms with ownership/control observations','adviser firms with disclosures','does this adviser have disciplinary history','adviser firms with state enforcement','what fee percentage does this firm charge','is this adviser fee-only','Schedule A/B ownership','how many Form ADV filings are there','how many ownership records are there','most recently filed Form ADV'];
const unsupported = ['RIAs in New Jersey','ERAs in California','advisers serving Florida','advisers with clients in Florida','advisers registered in New Jersey','New Jersey state RIAs','California state RIAs','Arizona state RIAs','historical Form ADV changes',"how did this firm's ADV change",'is this adviser SEC approved','is this adviser safe','safest financial adviser','best RIA','best financial adviser','most trustworthy adviser','adviser with best returns','which adviser should manage my money','which adviser will make me the most money','adviser with no disclosures','adviser with clean disciplinary history','adviser with no enforcement','does this adviser serve my ZIP code','adviser near me','IAR CRD 123456','individual adviser CRD 123456','ERAs with RAUM','<script>alert(1)</script>',"' OR 1=1 --",'', 'x'.repeat(500)];
export const INVESTOR_SEARCH_GOLDEN_QUESTIONS = [
  ...pass.map((query) => ({ query, expected: 'PASS' as const })),
  ...partial.map((query) => ({ query, expected: 'PARTIAL' as const })),
  ...unsupported.map((query) => ({ query, expected: 'UNSUPPORTED_SAFE' as const })),
];
