/** Generated by scripts/build-nj-public-snapshot.mjs. Do not edit by hand. */
export const NJ_PUBLIC_SNAPSHOT = {
  "version": "nj-inv-003-public-v1",
  "generatedFrom": {
    "auditedSnapshot": "artifacts/nj-inv-002-audited-state-snapshot.json",
    "coverageManifest": "artifacts/nj-inv-001c-enforcement-coverage.csv",
    "nationalRoster": "packages/domain/src/investor-home-intel.ts V1_ROSTER_PRINCIPAL_OFFICE_STATES"
  },
  "asOf": "2026-09-02",
  "publicationGate": "ON",
  "publicEligibility": "state_page",
  "route": "/new-jersey",
  "nationalOverlay": {
    "njPrincipalOfficeSecIardFirms": 438,
    "grain": "SEC IARD roster firm with principal-office region = NJ",
    "source": "IA_FIRM_SEC_Feed_08_27_2026",
    "sourceDate": "2026-08-27",
    "retrievedAt": "2026-08-28",
    "universe": 23622,
    "caveat": "This is the national SEC/IARD roster overlay. It is not the New Jersey state-registered adviser universe and does not include ERAs or state-only firms unless they appear in that roster with a NJ principal office.",
    "searchHref": "/firms?state=NJ"
  },
  "enforcement": {
    "acquiredDocuments": 48,
    "uniqueHashes": 48,
    "coverage": "ACQUIRED_PARTIAL_HISTORY",
    "earliest": "2002-08-22",
    "latest": "2026-02-25",
    "latestNote": "Patel/Arya International summary cease-and-desist hosted by NJOAG, February 25, 2026.",
    "byYear": {
      "2002": 1,
      "2003": 2,
      "2009": 1,
      "2010": 1,
      "2012": 1,
      "2013": 4,
      "2014": 1,
      "2015": 3,
      "2016": 5,
      "2017": 6,
      "2018": 3,
      "2019": 2,
      "2020": 3,
      "2021": 1,
      "2023": 2,
      "2024": 3,
      "2025": 3,
      "2026": 1,
      "unknown": 5
    },
    "byClass": {
      "consent_order": 24,
      "cease_and_desist": 2,
      "other_bureau_document": 7,
      "revocation": 10,
      "summary_order": 3,
      "civil_complaint": 1,
      "final_order": 1
    },
    "coverageLabel": "Partial historical corpus — the Bureau's live action index is access-blocked and the acquired documents do not establish the complete universe of actions.",
    "doNotCalculateEnforcementRate": true
  },
  "exam": {
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "currentYear": 2026,
    "deadline": "2026-06-30",
    "questionCount2026": 68,
    "passFailMetric": false,
    "firmResults": "SOURCE_NOT_PUBLIC_AT_FIRM_GRAIN",
    "roundedPopulationContext": [
      "nearly 900",
      "nearly 800"
    ],
    "timeline": [
      {
        "topic": "ADVERTISING_MARKETING",
        "label": "Advertising and marketing",
        "firstYear": 2024,
        "yearsPresent": [
          2024,
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "ARTIFICIAL_INTELLIGENCE",
        "label": "Artificial intelligence",
        "firstYear": 2024,
        "yearsPresent": [
          2024
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "AUM_OR_ASSETS",
        "label": "Assets under management",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "COMPLAINTS",
        "label": "Complaints",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "COMPLIANCE_POLICIES",
        "label": "Compliance policies",
        "firstYear": 2022,
        "yearsPresent": [
          2022,
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "CONFLICTS_OF_INTEREST",
        "label": "Conflicts of interest",
        "firstYear": 2025,
        "yearsPresent": [
          2025
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "CRYPTOCURRENCY",
        "label": "Cryptocurrency",
        "firstYear": 2022,
        "yearsPresent": [
          2022
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "CUSTODY",
        "label": "Custody",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "CYBERSECURITY",
        "label": "Cybersecurity",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "DIGITAL_ASSETS",
        "label": "Digital assets",
        "firstYear": 2022,
        "yearsPresent": [
          2022
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "DISCRETION",
        "label": "Discretion",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "FINANCIAL_CONDITION",
        "label": "Financial condition",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "FIRM_ORGANIZATION",
        "label": "Firm organization",
        "firstYear": 2023,
        "yearsPresent": [
          2023,
          2024,
          2025,
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "INVESTMENT_CONCENTRATION",
        "label": "Investment concentration",
        "firstYear": 2024,
        "yearsPresent": [
          2024
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "NFT",
        "label": "Non-fungible tokens (NFTs)",
        "firstYear": 2022,
        "yearsPresent": [
          2022
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "OUTSIDE_BUSINESS_ACTIVITIES",
        "label": "Outside business activities",
        "firstYear": 2025,
        "yearsPresent": [
          2025,
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "REPRESENTATIVE_OVERSIGHT",
        "label": "Representative oversight",
        "firstYear": 2025,
        "yearsPresent": [
          2025,
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "VENDOR_DUE_DILIGENCE",
        "label": "Vendor / third-party platforms",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      },
      {
        "topic": "VULNERABLE_ADULTS",
        "label": "Vulnerable adults / senior investors",
        "firstYear": 2026,
        "yearsPresent": [
          2026
        ],
        "sourceSupport": "official_sample_or_announcement"
      }
    ],
    "timelineByYear": [
      {
        "year": 2022,
        "topics": [
          "Compliance policies",
          "Cryptocurrency",
          "Digital assets",
          "Non-fungible tokens (NFTs)"
        ],
        "caveat": "Themes are taken from official Bureau/NJOAG announcements. A missing sample questionnaire is not evidence that a topic was removed."
      },
      {
        "year": 2023,
        "topics": [
          "Firm organization"
        ],
        "caveat": "Themes are taken from official Bureau/NJOAG announcements. A missing sample questionnaire is not evidence that a topic was removed."
      },
      {
        "year": 2024,
        "topics": [
          "Advertising and marketing",
          "Artificial intelligence",
          "Firm organization",
          "Investment concentration"
        ],
        "caveat": "Themes are taken from official Bureau/NJOAG announcements. A missing sample questionnaire is not evidence that a topic was removed."
      },
      {
        "year": 2025,
        "topics": [
          "Conflicts of interest",
          "Firm organization",
          "Outside business activities",
          "Representative oversight"
        ],
        "caveat": "Themes are taken from official Bureau/NJOAG announcements. A missing sample questionnaire is not evidence that a topic was removed."
      },
      {
        "year": 2026,
        "topics": [
          "Advertising and marketing",
          "Assets under management",
          "Complaints",
          "Compliance policies",
          "Custody",
          "Cybersecurity",
          "Discretion",
          "Financial condition",
          "Firm organization",
          "Outside business activities",
          "Representative oversight",
          "Vendor / third-party platforms",
          "Vulnerable adults / senior investors"
        ],
        "caveat": "Themes are taken from the official 2026 public sample examination PDF."
      }
    ],
    "consumerSafeStatement": "The written examination is not a public firm rating or pass/fail credential. Firm answers are not public."
  },
  "issuer": {
    "filingClasses": [
      {
        "id": "PRIVATE_PLACEMENT_REPORT",
        "label": "Private placement report of sale"
      },
      {
        "id": "SCOR_REGISTRATION",
        "label": "Small corporate offering registration (SCOR)"
      },
      {
        "id": "INVESTMENT_COMPANY_NOTICE",
        "label": "Investment-company notice filing (covered securities)"
      },
      {
        "id": "FORM_D_NOTICE",
        "label": "Federal Form D copy when a NJ private-placement report includes it"
      },
      {
        "id": "CROWDFUNDING_EXEMPTION",
        "label": "Intrastate crowdfunding exemption"
      },
      {
        "id": "CROWDFUNDING_INVESTOR_CERTIFICATION",
        "label": "Crowdfunding investor certification form (not ingested as PII)"
      },
      {
        "id": "CROWDFUNDING_INVESTOR_LEGEND",
        "label": "Crowdfunding investor legend"
      },
      {
        "id": "INTERNET_SITE_OPERATOR",
        "label": "Internet Site Operator registration"
      },
      {
        "id": "ISO_AMENDMENT",
        "label": "Internet Site Operator amendment"
      },
      {
        "id": "ISSUER_AGENT_REGISTRATION",
        "label": "Agent of the issuer registration"
      },
      {
        "id": "RESCISSION_OFFER",
        "label": "Rescission-offer procedure"
      },
      {
        "id": "SECURITIES_REGISTRATION_U1",
        "label": "Uniform application to register securities (Form U-1)"
      }
    ],
    "publicIndex": false,
    "exemptionIsEndorsement": false,
    "caveat": "An exemption category or filing class is not approval, endorsement, or a finding that an offering is safe."
  },
  "policy": {
    "modeledCurrent": 2,
    "libraryCoverage": "SOURCE_ACCESS_BLOCKED",
    "isFirmEnforcement": false,
    "instruments": [
      {
        "title": "IAR continuing education requirement",
        "effectiveOn": "2025-01-01",
        "affected": "Investment adviser representatives",
        "note": "12 annual credits as described on the Bureau IAR CE FAQ. This is policy, not a person directory."
      },
      {
        "title": "IAR examination waiver designations",
        "effectiveOn": null,
        "affected": "Investment adviser representatives",
        "note": "Bureau examination-requirements page describes designation-based waivers. Not firm enforcement."
      }
    ]
  },
  "gaps": [
    "A complete current New Jersey state-registered investment adviser firm roster is pending an official records request.",
    "A complete historical Bureau enforcement index is unavailable through the current public HTML library (access-blocked).",
    "Public firm-level annual examination answers are not available.",
    "A complete public issuer / crowdfunding / Internet Site Operator filing index is not downloadable.",
    "Orders of general application HTML library remains access-blocked; two policy instruments are modeled from official public descriptions."
  ],
  "profileAttachments": [],
  "profileRule": "Attach Bureau evidence to a firm profile only on exact CRD/SEC file match or deterministic legal-name+address+class match. Name-only, DBA-only, review-required, unresolved, and synthetic matches are withheld.",
  "fingerprint": "dad2d1ae91c971c8bcc3f41900c68915464bf299ba4682aaf75c61c28288b0bb"
} as const;
export type NjPublicSnapshot = typeof NJ_PUBLIC_SNAPSHOT;
